### ISSUE TITLE
async_handle_push_notification

### ISSUE THREAD

**Issue by PachangaDad** [albertogeniola/meross-homeassistant#234]
Noob, first off

For sometime now, I have been receiving this repeating error in my (2) variations of Home Assistance I have running.
One Test environment the other in pseudo Production  
Both HA versions are running on Proxmox as VM's

Can you provide any guidance as where to look for my error?
I suspect this may have something to do with my Meross Temp Sensors via the Meross Hub.
I have noticed that I am not seeing temp changes when querying from Node-Red the specific entities.
Initial temperature value is shown and there after no changes in the temperature value is transmitted.

Again I'm a beginner and learning. I thank you in advance for your development.
Birger (PachangaDad)

**Your environment**
HomeAssistant version: **core-2021.5.5   supervisor-2021.04.3**
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: ProxMox VMs on Dell R610

**Logs taken when the issue happened**
```

This error originated from a custom integration.

Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:54
Integration: Meross Cloud IoT
First occurred: 5:04:02 PM (1 occurrences)
Last logged: 5:04:02 PM

=============================== Meross Cloud Custom component Developed by Alberto Geniola Low level library version: 0.4.1.0rc7 ------------------------------- This custom component is under development and not yet ready for production use. In case of errors/misbehave, please report it here: https://github.com/albertogeniola/meross-homeassistant/issues If you like this extension and you want to support it, please consider donating. ------------------------------- List of devices reported by HTTP API: - Pumphouse Surge - Main (mss425f) - OnlineStatus.ONLINE - Living room Wyze CAM (mss110) - OnlineStatus.ONLINE - Lab Tester Switch (mss110) - OnlineStatus.ONLINE - Smart Wall Switch (mss510x) - OnlineStatus.ONLINE - Meross Smart Hub (msh300) - OnlineStatus.ONLINE - Garage Surge - Main (sp425fw) - OnlineStatus.ONLINE ==============================
Logger: meross_iot.manager
Source: /usr/local/lib/python3.8/site-packages/meross_iot/manager.py:496
First occurred: 5:05:08 PM (24 occurrences)
Last logged: 5:07:37 PM

An unhandled exception occurred while handling push notification
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/meross_iot/manager.py", line 493, in _async_dispatch_push_notification
    handled = await dev.async_handle_push_notification(namespace=push_notification.namespace,
  File "/usr/local/lib/python3.8/site-packages/meross_iot/controller/known/subdevice.py", line 58, in async_handle_push_notification
    for sample in samples:
TypeError: 'NoneType' object is not iterable
```

**Comment by albertogeniola** [comment]
This should be fixed in ab3fa51b88a0bbf56b4a15d98307e4e2fa8b91c2 (released in v1.1.2). Can you test that and let me know?

**Comment by PachangaDad** [comment]
Hi,
I now have the v1.1.4 which was a rolled back this morning via HACS notification from v1.1.5c1 version.

Still receiving the following logs repeatedly. 

2021-09-01 10:51:18 ERROR (MainThread) [meross_iot.manager] An unhandled exception occurred while handling push notification
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 724, in _async_dispatch_push_notification
await dev.async_handle_push_notification(
File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/known/subdevice.py", line 53, in async_handle_push_notification
for sample in samples:
TypeError: 'NoneType' object is not iterable
2021-09-01 10:51:18 ERROR (MainThread) [meross_iot.manager] An unhandled exception occurred while handling push notification
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 724, in _async_dispatch_push_notification
await dev.async_handle_push_notification(
File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/known/subdevice.py", line 53, in async_handle_push_notification
for sample in samples:
TypeError: 'NoneType' object is not iterable
