### ISSUE TITLE
MSS310 Meross smart plug / power consumption is not transmitted to home assistant

### ISSUE THREAD

**Issue by DerLoco** [albertogeniola/meross-homeassistant#293]
**Describe the bug**

Since last HA update 2021.12 the current enerhy usage is not transmitted to HA. Power usage remains 0,0 W even a plugin in device (a laundry in this case) is running.

**Your environment**
HomeAssistant version: core-2021.12.3
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: rpi4-64

**Logs taken when the issue happened**
```
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.2.2
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here:
https://github.com/albertogeniola/meross-homeassistant/issues
If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Trockner (mss310) - OnlineStatus.ONLINE
- Weihnachtsbaum (mss210) - OnlineStatus.ONLINE
- Smart Outdoor Plug (mss620) - OnlineStatus.ONLINE
- Smart Ambient Light (msl420) - OnlineStatus.ONLINE
- Smart Plug (mss210) - OnlineStatus.OFFLINE
===============================
2021-12-18 18:00:11 WARNING (MainThread) [meross_iot.manager] Device Smart Plug (2012101851256851853348e1e93f59b9) was built statically via known types, because we failed to retrieve updated abilities for the given device.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Device Smart Outdoor Plug (#BASE:2005216440907890813548e1e91ce6fb) has been already added to the registry.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Device Smart Ambient Light (#BASE:2101264730347090840948e1e948fed3) has been already added to the registry.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Found a new device Trockner (mss310, HW 6.0.0, FW 6.1.10, class: mss310:6.0.0:6.1.10) that has become online while we were offline.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Found a new device Weihnachtsbaum (mss210, HW 4.0.0, FW 4.2.5, class: mss210:4.0.0:4.2.5) that has become online while we were offline.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Found a new device Smart Outdoor Plug (mss620, HW 4.0.0, FW 4.1.32, class: mss620:4.0.0:4.1.32) that has become online while we were offline.
2021-12-18 18:00:12 WARNING (MainThread) [meross_iot.manager] Found a new device Smart Ambient Light (msl420, HW 4.0.0, FW 4.2.5, class: msl420:4.0.0:4.2.5) that has become online while we were offline.
2021-12-18 18:00:24 WARNING (Thread-32) [matplotlib.font_manager] Matplotlib is building the font cache; this may take a moment.
2021-12-18 18:05:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.trockner_mss310_power_sensor_a_0 has unit A which is unsupported for device_class power
2021-12-18 18:05:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.trockner_mss310_power_sensor_v_0 has unit V which is unsupported for device_class power
```

**Comment by AlainGH** [comment]
Same issue here with both my mss310

**Your environment**
HomeAssistant version: core-2021.12.0
Hassio Version (if applicable): -- PLEASE SPECIFY --
Hardware environment: rpi3B+

**Comment by albertogeniola** [comment]
Hi,

This should be fixed in v1.2.0rc0.

Can you please test that and report if it works now?

**Comment by AlainGH** [comment]
Hi, it seems the problem is not solved but I'll keep on testing

**Comment by albertogeniola** [comment]
Can you provide some screenshots ?

**Comment by AlainGH** [comment]
I'm quite sure the appliances connected to the 2 smart plugs worked each at least once today but HA always recorded 0 power.
![storico_lavastoviglie](https://user-images.githubusercontent.com/66970140/149404551-5c7648d5-89dd-43d4-b3fa-9b3921203051.jpg)
![storico_lavatrice](https://user-images.githubusercontent.com/66970140/149404564-834c0177-a599-4973-940e-ee054818ce6b.jpg)
(nearly at 17:00 raspberry pi seem crashed, I restarted it about 90 minutes later
Here's HA log
![log](https://user-images.githubusercontent.com/66970140/149405146-4d947215-fac5-4c1e-ae68-d2212c80d8f6.jpg)

**Comment by AlainGH** [comment]
After a couple of restart, now they are back to work

**Comment by AlainGH** [comment]
Too bad it stops working from time to time and I'm forced to reload the integration.
It had never happened before 2021.12

**Comment by AlainGH** [comment]
About 1 week since upgrade to 1.2.0rc2 and everything seem fine

**Comment by d4rshy** [comment]
Hi,
I'm also having problems with it not registering the consumption. The Meross app does register it without problem.
I have to reload the integration every day for it to work.
I have  updated the plugs to the latest firmware and also updated the integration in Home Assistant.
I have the same problem with the 3 plugs I use.
I'm running Home Assistant Core as a docker on Unraid.

If I need to provide something to help please do not hesitate to ask.

Thanks for your help.
