### ISSUE TITLE
Merros IOT Cloud Fails to load on 2025.3.0

### ISSUE THREAD

**Issue by JosephRDawson** [albertogeniola/meross-homeassistant#542]
**Describe the bug**
Merros IOT Cloud Fails to load on 2025.3.0

**Your environment**
HomeAssistant version: 2025.3.0
Hassio Version (if applicable): Latest
Hardware environment: HA Greene
**Logs taken when the issue happened**
```
Logger: homeassistant.setup
Source: setup.py:275
First occurred: 6:46:58 PM (1 occurrences)
Last logged: 6:46:58 PM

Setup failed for custom integration 'meross_cloud': Requirements for meross_cloud not found: ['meross_iot==0.4.7.3'].

```

**Comment by MoWeBo** [comment]
+1

**Comment by alexruperez** [comment]
+1

**Comment by lorenzo-randisi** [comment]
+1

**Comment by mrlordziemniak** [comment]
same here:

Unable to install package meross_iot==0.4.7.3: × No solution found when resolving dependencies: ╰─▶ Because meross-iot==0.4.7.3 depends on paho-mqtt>=1.5.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that meross-iot==0.4.7.3 cannot be used. And because you require meross-iot==0.4.7.3, we can conclude that your requirements are unsatisfiable.

**Comment by JosephRDawson** [comment]
Sadly Meross LAN is broken on NEW devices using the 7.X firmware. The local encryption or something they are doing means none of my MS110 7.3.46 devices work under Meross LAN. All your devices will show but you will not be able to control all decides with new firmware on Meross LAN sadly. It works fine on old firmware but not all new ones.

**Comment by thiagopinto-42q** [comment]
+1

**Comment by Audio-Lefty** [comment]
+1

**Comment by turtle2472** [comment]
+1

... and watching for resolution.

**Comment by doenau** [comment]
+1

**Comment by chrisgick** [comment]
+1 Reverted to 2025.2.5 backup

**Comment by kostas-williams** [comment]
+1 reverted to last 2025.2 backup

**Comment by michalw2-alt** [comment]
+1

**Comment by Florian-Schmidt** [comment]
+1

**Comment by MRSOFT69** [comment]
+1

**Comment by b0l0k** [comment]
cc https://github.com/albertogeniola/meross-homeassistant/issues/541, https://github.com/albertogeniola/meross-homeassistant/issues/539

This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x https://github.com/mmatuska/MerossIot/tree/paho-mqtt-2.x.

So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:  
```
  "requirements": ["meross_iot==0.4.7.3"],
```

with
```
  "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
```

**Comment by Florian-Schmidt** [comment]
@b0l0k Works, thanks!

**Comment by giugit** [comment]
+1

**Comment by darynwilkinson** [comment]
+1

**Comment by Vladx71** [comment]
+1

**Comment by Iosmio** [comment]
> cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> 
> This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> 
> So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> 
> ```
>   "requirements": ["meross_iot==0.4.7.3"],
> ```
> 
> with
> 
> ```
>   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> ```

Gracias

**Comment by JosephRDawson** [comment]
@Iosmio ... THANK YOU! This worked.

**Comment by MRSOFT69** [comment]
@b0l0k nice its works!

**Comment by uta2000** [comment]
@b0l0k thank you so much!

**Comment by rpitera** [comment]
> cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> 
> This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> 
> So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> 
> ```
>   "requirements": ["meross_iot==0.4.7.3"],
> ```
> 
> with
> 
> ```
>   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> ```

Interesting. Not only did this fix the integration, but it may have also solved a problem I was having with authentication issues with fitbit and tuya. For awhile, every time I had to restart HA I have had to reauthenticate those two integrations. While they both authenticated quickly and correctly each time it was getting annoying and I started researching to see if anyone else was having this issue.  I found this post: 

https://community.home-assistant.io/t/every-reboot-authentication-expired-tuya-google-fit-fitbit/848894/6?u=rpitera 

and in it the other user said that when he deleted the Merros IOT integration the authentication issues went away.  I just applied your work-around and after restarting HA I didn't get the authentication issues for the first time in weeks. I wonder if the two things are truly related?

**Comment by thomasbidou** [comment]
+1

**Comment by Coolmanchambers** [comment]
> cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> 
> This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> 
> So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> 
> ```
>   "requirements": ["meross_iot==0.4.7.3"],
> ```
> 
> with
> 
> ```
>   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> ```

Confirmed works for me as well.  Thanks @b0l0k!

**Comment by darouss99** [comment]
> Interesting. Not only did this fix the integration, but it may have also solved a problem I was having with authentication issues with fitbit and tuya. For awhile, every time I had to restart HA I have had to reauthenticate those two integrations. While they both authenticated quickly and correctly each time it was getting annoying and I started researching to see if anyone else was having this issue. I found this post:
> 
> https://community.home-assistant.io/t/every-reboot-authentication-expired-tuya-google-fit-fitbit/848894/6?u=rpitera
> 
> and in it the other user said that when he deleted the Merros IOT integration the authentication issues went away. I just applied your work-around and after restarting HA I didn't get the authentication issues for the first time in weeks. I wonder if the two things are truly related?

Hi, I had the same issue. But affected Alarm.com and Google Calendar too, the calendar was disapearing after a reboot. I changed the requirement and it fixed the Calendar, Alarm.com integration and Tuya.

**Comment by jesuspicornell** [comment]
+1

**Comment by omriasta** [comment]
Apologies, Credit for the pull request should be for https://github.com/albertogeniola/meross-homeassistant/issues/542#issuecomment-2703051746

**Comment by jeffreyvangorkum** [comment]
This solved it for me, thanks!

**Comment by ScourFly** [comment]
+1

**Comment by dsvirdiau** [comment]
@b0l0k Thank you. https://github.com/albertogeniola/meross-homeassistant/issues/542#issuecomment-2703051746 worked for me too. Cheers

**Comment by Bertk** [comment]
> same here:
> 
> Unable to install package meross_iot==0.4.7.3: × No solution found when resolving dependencies: ╰─▶ Because meross-iot==0.4.7.3 depends on paho-mqtt>=1.5.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that meross-iot==0.4.7.3 cannot be used. And because you require meross-iot==0.4.7.3, we can conclude that your requirements are unsatisfiable.

Same problem here (HW: home assistant yellow)

```
Logger: homeassistant.util.package
Quelle: util/package.py:159
Erstmals aufgetreten: 05:53:28 (3 Vorkommnisse)
Zuletzt protokolliert: 05:53:30

Unable to install package meross_iot==0.4.7.3: × No solution found when resolving dependencies: ╰─▶ Because meross-iot==0.4.7.3 depends on paho-mqtt>=1.5.0,<2.0.0 and paho-mqtt==2.1.0, we can conclude that meross-iot==0.4.7.3 cannot be used. And because you require meross-iot==0.4.7.3, we can conclude that your requirements are unsatisfiable.
```

**Comment by NiTnEuQs** [comment]
+1

**Comment by m4tthall73** [comment]
+1

**Comment by v11t** [comment]
+1

**Comment by Jean88230** [comment]
Enregistreur: homeassistant.setup
Source: setup.py:275
S'est produit pour la première fois: 13:18:16 (2 occurrences)
Dernier enregistrement: 13:18:28

Setup failed for custom integration 'meross_cloud': Requirements for meross_cloud not found: ['meross_iot==0.4.7.3'].
Setup failed for custom integration 'ecoflow_cloud': Requirements for ecoflow_cloud not found: ['paho-mqtt==1.6.1'].

**Comment by danielgospodinow** [comment]
+1

**Comment by Thomascollu** [comment]
Solution work! tnks!!!

**Comment by rpitera** [comment]
@mauromorello - Sad to say that with the hotfix in this thread, it's back today after restarting for a core update.

Any chance you have a link or reference to the hotfix you're mentioning? I'd be willing to give it a try.

**Comment by roberttco** [comment]
I guess I'm dumb - where is this proverbial manifest file that can be edited ?  I was able to modify the requirements.txt file by copying a modified version to the container. then I called pip to install the updated Paho version and restarted the container but meross-iot 4.7.5 is not compatible.  So...

**Comment by towerrh** [comment]
`  "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`

This is also not working for me.

Im getting an "Invalid requirement"

**Comment by towerrh** [comment]
> cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> 
> This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> 
> So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> 
> ```
>   "requirements": ["meross_iot==0.4.7.3"],
> ```
> 
> with
> 
> ```
>   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> ```

`Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'`
Im getting the following error when trying the hot fix.

**Comment by DarylMc** [comment]
> I guess I'm dumb - where is this proverbial manifest file that can be edited ? I was able to modify the requirements.txt file by copying a modified version to the container. then I called pip to install the updated Paho version and restarted the container but meross-iot 4.7.5 is not compatible. So...
nano config/custom_components/meross_cloud/manifest.json

**Comment by JosephRDawson** [comment]
@roberttco Your not dumb it is not obvious to anyone not technical.

My first comment would be to go into Settings / Add-Ons  and go into the add-ons store and get "studio code server" 

[https://github.com/hassio-addons/addon-vscode](url)

That add-on will allow you to edit any file on your Home Assistant.  

Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder.
In that folder if you click on the manifest.json file.

In that file you will find a line that says...

`  "requirements": ["meross_iot==0.4.7.3"],`

You need to replace that file with ....

`  "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`

Then restart you home assistant and all should work.

**Comment by towerrh** [comment]
> [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> 
> My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> 
> [https://github.com/hassio-addons/addon-vscode](url)
> 
> That add-on will allow you to edit any file on your Home Assistant.
> 
> Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> 
> In that file you will find a line that says...
> 
> ` "requirements": ["meross_iot==0.4.7.3"],`
> 
> You need to replace that file with ....
> 
> ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> 
> Then restart you home assistant and all should work.

That no longer works :(

**Comment by JosephRDawson** [comment]
@towerrh how is it not working for you? 

This is still working for me on 2025.3.1

![Image](https://github.com/user-attachments/assets/e03e60ec-5a3b-4275-a5bf-87db5409f4cd)

**Comment by JosephRDawson** [comment]
My bigger question is @albertogeniola still working on this project?  I haven't seen him comment on any issues on this project for a while.  I am wondering if this project needs a new fork?  The Merros Lan project is slowly not working on newer firmware so this Merros Iot project is critical.   Hopefully someone can support this project going forward because their hasn't been any new releases for over 4 months.

**Comment by towerrh** [comment]
> [@towerrh](https://github.com/towerrh) how is it not working for you?
> 
> This is still working for me on 2025.3.1
> 
> ![Image](https://github.com/user-attachments/assets/e03e60ec-5a3b-4275-a5bf-87db5409f4cd)
> 
> Also note spacing and indentation is critical.

Absolutely. Tried that and restarted. Im getting this error..

```
Logger: homeassistant.util.package
Source: util/package.py:63
First occurred: 7:09:11 PM (2 occurrences)
Last logged: 7:09:12 PM

Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'
```

**Comment by roberttco** [comment]
> [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> 
> My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> 
> [https://github.com/hassio-addons/addon-vscode](url)
> 
> That add-on will allow you to edit any file on your Home Assistant.
> 
> Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> 
> In that file you will find a line that says...
> 
> ` "requirements": ["meross_iot==0.4.7.3"],`
> 
> You need to replace that file with ....
> 
> ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> 
> Then restart you home assistant and all should work.

Ahh _THAT_ manifest file.  Thank you.  I thought it was some manifest file inside the container - which I couldn't find.   This does fix the issue for me (HA version 2025.3.0).  Hopefully this will be a "real" fix soon.

**Comment by JosephRDawson** [comment]
Can you publish a image or copy of your manifest.json file?

**Comment by JosephRDawson** [comment]
@roberttco I hope your right but the owner of this project hasn't released an update in quite a while so I am not sure it will.

**Comment by towerrh** [comment]
> [@towerrh](https://github.com/towerrh) Can you publish a image or copy of your manifest.json file?


Absolutely!

`{
  "domain": "meross_cloud",
  "name": "Meross Cloud IoT",
  "documentation": "https://www.home-assistant.io/components/meross_cloud",
  "issue_tracker": "https://github.com/albertogeniola/meross-homeassistant",
  "dependencies": ["persistent_notification"],
  "codeowners": ["@albertogeniola"],
  "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
  "config_flow": true,
  "quality_scale": "platinum",
  "iot_class": "cloud_push",
  "version": "1.3.3"
}
`

**Comment by towerrh** [comment]
> [@towerrh](https://github.com/towerrh) Can you publish a image or copy of your manifest.json file?

![Image](https://github.com/user-attachments/assets/39545d22-07eb-42a3-b952-82298c7bea92)

**Comment by DarylMc** [comment]
> [@towerrh](https://github.com/towerrh) Can you publish a image or copy of your manifest.json file?

![Image](https://github.com/user-attachments/assets/a05da50c-ff3e-4184-b687-9127b8471ca5)

**Comment by JosephRDawson** [comment]
@DarylMc  is that working for you now?

**Comment by towerrh** [comment]
> > [@towerrh](https://github.com/towerrh) Can you publish a image or copy of your manifest.json file?
> 
> ![Image](https://github.com/user-attachments/assets/a05da50c-ff3e-4184-b687-9127b8471ca5)

Yea. Unfortunately it doesnt work for me. 

[manifest.json](https://github.com/user-attachments/files/19140694/manifest.json)

**Comment by DarylMc** [comment]
> [@DarylMc](https://github.com/DarylMc) is that working for you now?

yes

**Comment by JosephRDawson** [comment]
@towerrh  I have no explanation for you... Unless it is somehow a bad character that is not being shown.

On the remote chance this is that I have dropped my file into dropbox here
https://www.dropbox.com/scl/fi/aaig08rayrhpw6bejbidm/manifest.json?rlkey=v28mcumz21mb96pg07b01sqca&st=9dszlawc&dl=0

Your welcome to try my working file.
The fact @DarylMc just got it working means the method should still be working for you today.

I can only guess you have somehow a bad character or bad spacing in your file.

**Comment by DarylMc** [comment]
@JosephRDawson @towerrh 
It may be wrong text formatting?
See the hyperlink in this picture attached.

![Image](https://github.com/user-attachments/assets/b585bf58-4431-4348-b404-c1d2642513b7)

Also maybe double check the file path.

**Comment by wild-a** [comment]
> [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> 
> My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> 
> [https://github.com/hassio-addons/addon-vscode](url)
> 
> That add-on will allow you to edit any file on your Home Assistant.
> 
> Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> 
> In that file you will find a line that says...
> 
> ` "requirements": ["meross_iot==0.4.7.3"],`
> 
> You need to replace that file with ....
> 
> ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> 
> Then restart you home assistant and all should work.

I can confirm that this worked for me 2025.3.1

**Comment by Marra74** [comment]
> > [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> > My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> > [https://github.com/hassio-addons/addon-vscode](url)
> > That add-on will allow you to edit any file on your Home Assistant.
> > Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> > In that file you will find a line that says...
> > ` "requirements": ["meross_iot==0.4.7.3"],`
> > You need to replace that file with ....
> > ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> > Then restart you home assistant and all should work.
> 
> I can confirm that this worked for me 2025.3.1

Worked for me also... ;)

**Comment by AtonPC** [comment]
> > > [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> > > My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> > > [https://github.com/hassio-addons/addon-vscode](url)
> > > That add-on will allow you to edit any file on your Home Assistant.
> > > Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> > > In that file you will find a line that says...
> > > ` "requirements": ["meross_iot==0.4.7.3"],`
> > > You need to replace that file with ....
> > > ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> > > Then restart you home assistant and all should work.
> > 
> > 
> > I can confirm that this worked for me 2025.3.1
> 
> Worked for me also... ;)

A mi también me funcionó! Gracias!

**Comment by Korvenwin** [comment]
The manifest.json modification worked fine for me. Thank you very much

**Comment by mauromorello** [comment]
> [@mauromorello](https://github.com/mauromorello) - Sad to say that with the hotfix in this thread, it's back today after restarting for a core update.
> 
> Any chance you have a link or reference to the hotfix you're mentioning? I'd be willing to give it a try.

I think someone did this: 
https://github.com/albertogeniola/meross-homeassistant/pull/536

**Comment by RW-Allen** [comment]
+

Skipped 2025.3.0, but loaded 2025.3.1 this morning and had this issue.   Will forgo work around and will wait for fix.  For now have reverted back to 2025.2.5.

**Comment by kevinrkowalski** [comment]
+1 waiting for fix. rolled back to 2025.2.5

**Comment by JosephRDawson** [comment]
Just for @kevinrkowalski and @RW-Allen .... 

The owner of this github has not been active for a few months or made any posts in quite a while.  So it is not clear to me that any fix is coming. 

I did see @omriasta made a pull request so I am not sure if that requires the owner of this github to approve it or not. 

I would love to see the owner of this github @albertogeniola to post and make some comment on this to say he will make an update to this or if this is an old project for him and he has moved on. It is only fair enough that people will create code like this and not always want to support it for life. I totally understand if he has moved on to other things.

**Comment by mauromorello** [comment]
> > > [@towerrh](https://github.com/towerrh) Can you publish a image or copy of your manifest.json file?
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/a05da50c-ff3e-4184-b687-9127b8471ca5)
> 
> Yea. Unfortunately it doesnt work for me.
> 
> [manifest.json](https://github.com/user-attachments/files/19140694/manifest.json)

Try also to reboot entirely your system, not olnly restart HA

**Comment by RW-Allen** [comment]
> Just for [@kevinrkowalski](https://github.com/kevinrkowalski) and [@RW-Allen](https://github.com/RW-Allen) ....
> 
> The owner of this github has not been active for a few months or made any posts in quite a while. So it is not clear to me that any fix is coming.
> 
> I did see [@omriasta](https://github.com/omriasta) made a pull request so I am not sure if that requires the owner of this github to approve it or not.
> 
> I would love to see the owner of this github [@albertogeniola](https://github.com/albertogeniola) to post and make some comment on this to say he will make an update to this or if this is an old project for him and he has moved on. It is only fair enough that people will create code like this and not always want to support it for life. I totally understand if he has moved on to other things.

Thanks for the heads up, I see from his profile that he was last active (if i'm reading it right) on the 17th Feb, hopefully he will pick it up soon.  I can wait a while for a fix.

**Comment by kevinrkowalski** [comment]
> Just for [@kevinrkowalski](https://github.com/kevinrkowalski) and [@RW-Allen](https://github.com/RW-Allen) ....
> 
> The owner of this github has not been active for a few months or made any posts in quite a while. So it is not clear to me that any fix is coming.
> 
> I did see [@omriasta](https://github.com/omriasta) made a pull request so I am not sure if that requires the owner of this github to approve it or not.
> 
> I would love to see the owner of this github [@albertogeniola](https://github.com/albertogeniola) to post and make some comment on this to say he will make an update to this or if this is an old project for him and he has moved on. It is only fair enough that people will create code like this and not always want to support it for life. I totally understand if he has moved on to other things.

Yes, he will have to merge the request and push the update. Only other way is if someone forks this repo with the update and everyone moves over to that. Then we have no maintainer though

**Comment by jgpazos70** [comment]
> > cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> > This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> > So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> > ```
> >   "requirements": ["meross_iot==0.4.7.3"],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> >   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> > ```
> 
> `Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'` Im getting the following error when trying the hot fix.

Same error to me. I am using Home Assistant OS.

**Comment by fr3ddy-sudo** [comment]
Manifest edit work for me.

**Comment by jamdo63** [comment]
Manifest edit works like a charm.
Edit as above post for those scrolling:
https://github.com/albertogeniola/meross-homeassistant/issues/542#issuecomment-2707916018
Many thanks.

**Comment by jlr2000** [comment]
+1

**Comment by dalto12593** [comment]
> > [@roberttco](https://github.com/roberttco) Your not dumb it is not obvious to anyone not technical.
> > My first comment would be to go into Settings / Add-Ons and go into the add-ons store and get "studio code server"
> > [https://github.com/hassio-addons/addon-vscode](url)
> > That add-on will allow you to edit any file on your Home Assistant.
> > Once that add-on is installed you can navigate to /config/custom_components/merros_cloud folder. In that folder if you click on the manifest.json file.
> > In that file you will find a line that says...
> > ` "requirements": ["meross_iot==0.4.7.3"],`
> > You need to replace that file with ....
> > ` "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],`
> > Then restart you home assistant and all should work.
> 
> I can confirm that this worked for me 2025.3.1

Thank you!! Another success here.

Hopefully we can get this implemented natively with the pull request.

**Comment by gjbmcn** [comment]
+1

**Comment by donoverby** [comment]
This 'hotfix' worked for me. 
Thank you to the original author who put in a more detailed how to. As someone with a sloped forhead about this stuff I never would have figured this out.

**Comment by bupemko** [comment]
+1
Manifest.json edit worked for me as well running latest Home Assistant OS on a RPi4 (Core: 2025.3.1), thank you!
Mostly I have Matter enabled Meross devices doing power metering in HA so will have to dig into using Matter only in HA I guess if this is no longer maintained.

**Comment by helio4k** [comment]
Manifest edit work for me.
Thank You

**Comment by jgpazos70** [comment]
> > > cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> > > This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> > > So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> > > ```
> > >   "requirements": ["meross_iot==0.4.7.3"],
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with
> > > ```
> > >   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> > > ```
> > 
> > 
> > `Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'` Im getting the following error when trying the hot fix.
> 
> Same error to me. I am using Home Assistant OS.

Finally the workaround worked for me in 2025.3.1. Thank you.

**Comment by Leen15** [comment]
@albertogeniola Is there any plan to download an official version that fix this issue without any workaround?

Thanks

**Comment by batiatto** [comment]
I have HA 2025.3.1 and I did the requirements change in manifest.json. then I got this

```
Registrador: homeassistant.util.package
Fuente: util/package.py:63
Ocurrió por primera vez: 20:11:36 (2 ocurrencias)
Última vez registrado: 20:11:38

Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'
```

I'm running it from a docker container from an Ubuntu laptop.

**Comment by Coastersteve** [comment]
Worked a treat for me too. Thank you so much.

**Comment by pc-bastler** [comment]
Workaround does not work here:

Logger: homeassistant.setup
Quelle: setup.py:275
Erstmals aufgetreten: 21:10:17 (1 Vorkommnisse)
Zuletzt protokolliert: 21:10:17

Setup failed for custom integration 'meross_cloud': Requirements for meross_cloud not found: ['git+https://github.com/matuska/MerossIot.git@paho-mqtt-2.x'].

**Comment by JosephRDawson** [comment]
[manifest.json](https://github.com/user-attachments/files/19153753/manifest.json)

This is the fill Manifest file that should work.

**Comment by david-romero** [comment]
Fixed issue with the manifest hotfix. Thank you!

**Comment by xeno111** [comment]
Followed instructions which worked great, thank you

**Comment by psymon101** [comment]
Worked like a champ.. Thank you!!

**Comment by briefer666** [comment]
fixed with instructions, thanks

**Comment by shi-vy** [comment]
Manifest issue fix worked for me!  Thanks so much!

**Comment by fcouste** [comment]
fixed with instructions, thanks

**Comment by SpencerMcO** [comment]
For some reason, the fix https://github.com/albertogeniola/meross-homeassistant/issues/542#issuecomment-2707903116 doesn't work for me.

I'm on HAOS 2025.3.1 (running on Proxmox on my ~10 year old Mac mini) and made the recommended adjustment to the `manifest.json` file, but even though the error (the one indicated at the top of this issue) no longer popped up in Home Assistant, none of my Meross devices are responding. I even tried upgrading to HAOS 2025.3.2, with and without the edit to the `manifest.json` file, and it still didn't work.

Any advice on how I should troubleshoot this? I attached a snippet of my `manifest.json` in case I made a mistake:
![Image](https://github.com/user-attachments/assets/2bce7c90-b2f2-4c22-bdf0-9e682d64e2d8)

**Comment by JosephRDawson** [comment]
@SpencerMcO the lack of the error is odd.  I assume the error still shows up when you remove the modified text?  Or in both cases the error is not showing up?

This is very strange.

**Comment by GOTO-GOSUB** [comment]
Thanks to everyone involved in the hotfix, and also to @towerrh for the Studio Code Server recommendation that allowed me to repair a remote instance.

**Comment by JosephRDawson** [comment]
> Thanks to everyone involved in the hotfix, and also to [@towerrh](https://github.com/towerrh) for the Studio Code Server recommendation that allowed me to repair a remote instance.

I am glad you got that working...  I suggested @towerrh use "Studio Code Server"...  But I only did that because a friend told me about it 1.5 years ago when I got into HA.  Studio Code Server is wonderful it has allowed me to do many things with HA I wouldn't have been able to do without.

I am so glad you have been able to fix your issue.  I am getting to the point where I am concerned for @albertogeniola it is rare he is away from github this long without making any comments on a thread.  Hopefully he is just on vacation somewhere enjoying life and not ill.

**Comment by midadami** [comment]
I am on 2025.3.2 using HA OS on RaspberryPi4. While the hotfix works (devices are back online and updating) I can still see the error on log: 
```
Logger: homeassistant.util.package
Source: util/package.py:63
First occurred: 08:46:43 (2 occurrences)
Last logged: 08:46:52

Invalid requirement 'git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x'
```

Thanks a lot for the hotfix!!!

**Comment by mikefrantz** [comment]
Is there gonna be an upgrade to the integration so we don’t have to go in and change these files manually?

**Comment by JosephRDawson** [comment]
> Is there gonna be an upgrade to the integration so we don’t have to go in and change these files manually?

We don't know because the owner of this project hasn't been active in a while. So we don't have any idea.

**Comment by mikefrantz** [comment]
I manually changed the file and it worked for me. Thanks

**Comment by gcadoret** [comment]
thanks for the tips , even if now I know I must move to https://github.com/krahabb/meross_lan

**Comment by vlciho** [comment]
> cc [#541](https://github.com/albertogeniola/meross-homeassistant/issues/541), [#539](https://github.com/albertogeniola/meross-homeassistant/issues/539)
> 
> This is indeed a problem of dependency resolution on paho-mqtt referened in meross-iot. It already exists a PR updating it to 2.x [albertogeniola/MerossIot#413](https://github.com/albertogeniola/MerossIot/pull/413) .
> 
> So, if you want a hotfix, waiting new releases, you can edit `manifest.json` and replace this line:
> 
> ```
>   "requirements": ["meross_iot==0.4.7.3"],
> ```
> 
> with
> 
> ```
>   "requirements": ["git+https://github.com/mmatuska/MerossIot.git@paho-mqtt-2.x"],
> ```

Superb! Worked for me, thank you!

**Comment by benji2020** [comment]
+1 on the issue and hoping Alberto is all good.

Workaround/hotfix to the manifest worked.

**Comment by albertogeniola** [comment]
Duplicate of #544 . Please update to v1.3.4, which solves the issue. Thanks to everyone and sorry for the late fix!

**Comment by JosephRDawson** [comment]
> Duplicate of [#544](https://github.com/albertogeniola/meross-homeassistant/issues/544) . Please update to v1.3.4, which solves the issue. Thanks to everyone and sorry for the late fix!
> 
> And thanks to everyone for being so nice. Don't worry I'm just fine. I'm only getting busier (moved to a new apartment, getting married and so on :) )

Congradulations...

I don't see V1.3.4... It still shows 1.3.3 as the latest in HACS for me.

**Comment by mikefrantz** [comment]
I don't see V1.3.4... It still shows 1.3.3 as the latest in HACS for me either!

**Comment by mikefrantz** [comment]
After updating to your new version, I get this error. Is there something else I need to do? 
This error originated from a custom integration.

Logger: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:336
integration: Meross Cloud IoT
First occurred: 8:20:17 PM (1 occurrences)
Last logged: 8:20:17 PM

Returned/Stored DOMAIN within existing credentials is <https://iot.meross.com>. Patching the stored credentials with the correct value right away.

**Comment by JosephRDawson** [comment]
i now see the 1.3.4... making a backup and will test it.

**Comment by gabriele-latino** [comment]
For me 1.3.4 on 2025.3.3 did't fix the issue:

`Setup failed for custom integration 'meross_cloud': Requirements for meross_cloud not found: ['meross_iot==0.4.8.0'].`

I had to revert again the string in the manifest from `meross_iot` to `MerossIot.git@paho-mqtt-2.x`

**Comment by farbenblind** [comment]
> I had to revert again the string in the manifest from `meross_iot` to `MerossIot.git@paho-mqtt-2.x`

same for me

**Comment by JosephRDawson** [comment]
I just installed on to of the modified version and it worked.

**Comment by farbenblind** [comment]
> I just installed on to of the modified version and it worked.

That would have been the perfect outcome of this update. Any idea why this works for you? Running Meross on ZHA.

**Comment by bauzer714** [comment]
> > I just installed on to of the modified version and it worked.
> 
> I did the same thing, but the new version overwrote the modded manifest change.

Likewise, initially I used HACS to "redownload" the 1.3.4 version as it wasn't showing as an update. Today, 1.3.6 showed as an update when I logged in - performed the "update" and still working as expected.

**Comment by albertogeniola** [comment]
Sorry guys, v1.3.4 had a bug referencing a old meross-iot version. V1.3.6 should finally solve the issue. Sorry for that!

**Comment by JosephRDawson** [comment]
> Sorry guys, v1.3.4 had a bug referencing a old meross-iot version. V1.3.6 should finally solve the issue. Sorry for that!

I just updated to 1.3.6... but it still says v1.3.4... 

![Image](https://github.com/user-attachments/assets/55be8f02-0357-41b2-8b1f-ec1655db9dbb)

**Comment by albertogeniola** [comment]
> > Sorry guys, v1.3.4 had a bug referencing a old meross-iot version. V1.3.6 should finally solve the issue. Sorry for that!
> 
> I just updated to 1.3.6... but it still says v1.3.4...
> 
> ![Image](https://github.com/user-attachments/assets/55be8f02-0357-41b2-8b1f-ec1655db9dbb)

Please re-download via HACS and restart HA after that. Let me know if that solves!

**Comment by JosephRDawson** [comment]
> 
> Please re-download via HACS and restart HA after that. Let me know if that solves!

Yep... why did that happen?  Never seen that before?  Did you forget to update the version number in 1.3.6 at first or was it a HACS bug?

**Comment by JosephRDawson** [comment]
> 
> Please re-download via HACS and restart HA after that. Let me know if that solves!

Yep... why did that happen?  Never seen that before?  Did you forget to update the version number in 1.3.6 at first or was it a HACS bug?

**Comment by joryirving** [comment]
Mine went straight to 1.3.6 from 1.3.3 with an update. I did implement the workaround, but my integration is still working post-update. Thanks!

**Comment by albertogeniola** [comment]
> 
> > 
> > Please re-download via HACS and restart HA after that. Let me know if that solves!
> 
> Yep... why did that happen?  Never seen that before?  Did you forget to update the version number in 1.3.6 at first or was it a HACS bug?

My fault, code has been updated and tagged correctly, but version value in info.json was still wrong. 

So it seems it's now working as expected, so I am closing this issue. Thanks everyone!

**Comment by JosephRDawson** [comment]
> I was not able to get Meross Integration v1.3.6 running at all. I tried different versions of meross_iot and paho-mqtt. None of my combinations worked. So I needed to downgrade...
> 
> **Solution:** Therefore the only way was to re-install Meross Integration in HACS with v1.3.2 (which uses meross_iot==0.4.7.2b3)

Have you updated your HA to 2025.03.3?  Because if you have V1.3.2 shouldn't work?
The reason for the new version is because V1.3.2 will not work on the latest Home Assistant.
